# Generated by Django 2.0.3 on 2020-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, null=True)),
                ('bday', models.DateField()),
                ('sex', models.CharField(choices=[('1', 'boy'), ('2', 'girl')], max_length=5)),
                ('checked', models.BooleanField()),
            ],
        ),
    ]
