# Generated by Django 2.0.3 on 2020-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
