# Generated by Django 2.0.3 on 2020-03-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('publish', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
