# Generated by Django 2.0.3 on 2020-03-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200325_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=7),
        ),
    ]
