# Generated by Django 2.0.3 on 2020-03-26 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200325_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(default=datetime.datetime(2020, 3, 26, 15, 20, 36, 163934))),
                ('telephone', models.CharField(max_length=11, null=True)),
                ('addr', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, null=True)),
                ('city', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.AddField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 15, 20, 36, 163934)),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
