# Generated by Django 2.0.3 on 2020-03-26 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200326_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='au',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.AuthorDetail'),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 15, 25, 31, 947607)),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishDate',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 15, 25, 31, 948604)),
        ),
    ]
