# Generated by Django 2.0.3 on 2020-03-26 15:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20200326_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, null=True)),
                ('publishDate', models.DateField(default=datetime.datetime(2020, 3, 26, 15, 28, 5, 901279))),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('authors', models.ManyToManyField(to='app01.Author')),
                ('publishs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Publish')),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='publishDate',
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='authordetail',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2020, 3, 26, 15, 28, 5, 900282)),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
